In [1]:
import cptac

In [2]:
cptac.list_datasets()

,Description,Data reuse status,Publication link
Dataset name,,,
Brca,breast cancer,no restrictions,https://pubmed.ncbi.nlm.nih.gov/33212010/
Ccrcc,clear cell renal cell carcinoma (kidney),no restrictions,https://pubmed.ncbi.nlm.nih.gov/31675502/
Colon,colorectal cancer,no restrictions,https://pubmed.ncbi.nlm.nih.gov/31031003/
Endometrial,endometrial carcinoma (uterine),no restrictions,https://pubmed.ncbi.nlm.nih.gov/32059776/
Gbm,glioblastoma,no restrictions,https://pubmed.ncbi.nlm.nih.gov/33577785/
Hnscc,head and neck squamous cell carcinoma,no restrictions,https://pubmed.ncbi.nlm.nih.gov/33417831/
Lscc,lung squamous cell carcinoma,no restrictions,https://pubmed.ncbi.nlm.nih.gov/34358469/
Luad,lung adenocarcinoma,no restrictions,https://pubmed.ncbi.nlm.nih.gov/32649874/
Ovarian,high grade serous ovarian cancer,no restrictions,https://pubmed.ncbi.nlm.nih.gov/27372738/
Pdac,pancreatic ductal adenocarcinoma,no restrictions,https://pubmed.ncbi.nlm.nih.gov/34534465/
UcecConf,endometrial confirmatory carcinoma,password access only,unpublished
GbmConf,glioblastoma confirmatory,password access only,unpublished

In [3]:
cptac.download(dataset='pdac')

True

In [4]:
pdac = cptac.Pdac()

Loading pdac v1.0.........

C:\Users\varsh\miniconda3\Lib\site-packages\cptac\pdac.py:188: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_tumor = df_tumor.assign(
C:\Users\varsh\miniconda3\Lib\site-packages\cptac\pdac.py:188: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_tumor = df_tumor.assign(

In [1]:
import sys
print(sys.executable)

C:\Users\varsh\miniconda3\envs\cptac_env\python.exe

In [4]:
print(dir(cptac))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

In [1]:
import cptac
print(dir(cptac))

['Brca', 'CPTAC_BASE_DIR', 'Ccrcc', 'Coad', 'CptacError', 'CptacWarning', 'DATA_DIR', 'Gbm', 'HEADERS', 'Hnscc', 'INDEX', 'Lscc', 'Luad', 'NoInternetError', 'OPTIONS', 'OldPackageVersionWarning', 'Ov', 'Pdac', 'USER_AGENT', 'Ucec', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_exception_handler', '_get_cancer_class', '_load_options', '_warning_displayer', 'cancers', 'check_version', 'cptac', 'df_to_tree', 'download', 'download_cancer', 'download_text', 'exceptions', 'get_cancer_info', 'get_cancer_options', 'get_datatype_options', 'get_source_options', 'how_to_cite', 'init_files', 'list_datasets', 'path', 'pd', 'requests', 'sys', 'threading', 'tools', 'utils', 'version', 'version_check_thread', 'warnings']

In [2]:
import cptac
import pandas as pd
import os

pdac = cptac.Pdac()
print("PDAC loaded!")

PDAC loaded!

In [4]:
pdac.list_data_sources()

              Data type    Available sources
0                   CNV         [bcm, washu]
1          circular_RNA                [bcm]
2                 miRNA         [bcm, washu]
3     phosphoproteomics         [bcm, umich]
4            proteomics         [bcm, umich]
5       transcriptomics  [bcm, broad, washu]
6   ancestry_prediction         [harmonized]
7      somatic_mutation  [harmonized, washu]
8              clinical               [mssm]
9             follow-up               [mssm]
10      medical_history               [mssm]
11            cibersort              [washu]
12           hla_typing              [washu]
13         tumor_purity              [washu]
14                xcell              [washu]

In [5]:
os.makedirs("data", exist_ok=True)

pdac.get_clinical("mssm").to_csv("data/clinical.csv")
print("1. clinical done")

pdac.get_CNV("bcm").to_csv("data/CNV.csv")
print("2. CNV done")

pdac.get_circular_RNA("bcm").to_csv("data/circular_RNA.csv")
print("3. circular_RNA done")

pdac.get_miRNA("bcm").to_csv("data/miRNA.csv")
print("4. miRNA done")

pdac.get_phosphoproteomics("bcm").to_csv("data/phosphoproteomics.csv")
print("5. phosphoproteomics done")

pdac.get_proteomics("bcm").to_csv("data/proteomics.csv")
print("6. proteomics done")

pdac.get_transcriptomics("bcm").to_csv("data/transcriptomics.csv")
print("7. transcriptomics done")

pdac.get_ancestry_prediction("harmonized").to_csv("data/ancestry_prediction.csv")
print("8. ancestry_prediction done")

pdac.get_somatic_mutation("harmonized").to_csv("data/somatic_mutation.csv")
print("9. somatic_mutation done")

pdac.get_followup("mssm").to_csv("data/followup.csv")
print("10. followup done")

pdac.get_medical_history("mssm").to_csv("data/medical_history.csv")
print("11. medical_history done")

pdac.get_cibersort("washu").to_csv("data/cibersort.csv")
print("12. cibersort done")

pdac.get_hla_typing("washu").to_csv("data/hla_typing.csv")
print("13. hla_typing done")

pdac.get_tumor_purity("washu").to_csv("data/tumor_purity.csv")
print("14. tumor_purity done")

pdac.get_xcell("washu").to_csv("data/xcell.csv")
print("15. xcell done")

print("ALL 15 CSV FILES SAVED!")

Downloading clinical_Pan-cancer.May2022.tsv.gz: 100%|████████████████████████████████| 243k/243k [00:00<00:00, 715kB/s]

1. clinical done

Downloading PDAC_WES_CNV_gene_ratio_log2.txt.gz: 100%|██████████████████████████████| 611k/611k [00:00<00:00, 1.39MB/s]
Downloading gencode.v34.basic.annotation-mapping.txt.gz: 100%|████████████████████| 1.75M/1.75M [00:01<00:00, 1.36MB/s]

2. CNV done

Downloading PDAC-circRNA_rsem_tumor_normal_UQ_log2(x+1)_BCM.txt.gz: 100%|████████████| 344k/344k [00:00<00:00, 937kB/s]

3. circular_RNA done

Downloading PDAC_miRNAseq_mature_miRNA_RPM_log2_Tumor.txt.gz: 100%|██████████████████| 306k/306k [00:00<00:00, 725kB/s]
Downloading PDAC_miRNAseq_mature_miRNA_RPM_log2_Normal.txt.gz: 100%|███████████████| 48.6k/48.6k [00:00<00:00, 179kB/s]

4. miRNA done

Downloading PDAC_phospho_site_abundance_log2_reference_intensity_normalized_Tumor.txt: 100%|█| 48.7M/48.7M [00:03<00:00
Downloading PDAC_phospho_site_abundance_log2_reference_intensity_normalized_Normal.txt.gz: 100%|█| 8.59M/8.59M [00:00<0

5. phosphoproteomics done

Downloading PDAC_proteomics_gene_abundance_log2_reference_intensity_normalized_Tumor.txt.gz: 100%|█| 7.38M/7.38M [00:01
Downloading PDAC_proteomics_gene_abundance_log2_reference_intensity_normalized_Normal.txt.gz: 100%|█| 3.17M/3.17M [00:0

6. proteomics done

Downloading PDAC-gene_rsem_removed_circRNA_tumor_normal_UQ_log2(x+1)_BCM.txt.gz: 100%|█| 14.7M/14.7M [00:01<00:00, 10.1

7. transcriptomics done

Downloading washu_mssm_consensus_ancestries.tsv.gz: 100%|█████████████████████████| 6.14k/6.14k [00:00<00:00, 24.3kB/s]

8. ancestry_prediction done

Downloading PanCan_Union_Maf_Broad_WashU_v1.1.maf.gz: 100%|████████████████████████▉| 138M/138M [00:08<00:00, 15.5MB/s]

9. somatic_mutation done
10. followup done
11. medical_history done

Downloading CIBERSORT.Output_Abs_PDA.txt.gz: 100%|████████████████████████████████| 30.0k/30.0k [00:00<00:00, 73.9kB/s]

12. cibersort done

Downloading hla.sample.ct.10152021.sort.tsv.gz: 100%|█████████████████████████████| 12.4k/12.4k [00:00<00:00, 48.5kB/s]

13. hla_typing done

Downloading CPTAC_pancan_RNA_tumor_purity_ESTIMATE_WashU.tsv.gz: 100%|████████████| 31.1k/31.1k [00:00<00:00, 81.5kB/s]

14. tumor_purity done

Downloading PDA_xCell.txt.gz: 100%|███████████████████████████████████████████████| 17.9k/17.9k [00:00<00:00, 59.0kB/s]

15. xcell done
ALL 15 CSV FILES SAVED!

In [6]:
import os
print("Current folder:", os.getcwd())
print("\nFiles in data folder:")
for f in os.listdir("data"):
    size_mb = os.path.getsize(f"data/{f}") / (1024*1024)
    print(f"  {f} - {size_mb:.2f} MB")

Current folder: C:\Users\varsh

Files in data folder:
  ancestry_prediction.csv - 0.01 MB
  cibersort.csv - 0.06 MB
  circular_RNA.csv - 3.63 MB
  clinical.csv - 0.23 MB
  CNV.csv - 39.76 MB
  followup.csv - 0.00 MB
  hla_typing.csv - 0.01 MB
  medical_history.csv - 0.00 MB
  miRNA.csv - 1.54 MB
  phosphoproteomics.csv - 64.99 MB
  proteomics.csv - 22.01 MB
  somatic_mutation.csv - 0.00 MB
  transcriptomics.csv - 57.85 MB
  tumor_purity.csv - 0.01 MB
  xcell.csv - 0.07 MB

In [7]:
import shutil
import os

source = r"C:\Users\varsh\data"
destination = r"C:\Users\varsh\Documents\R\cptac_pdac_pca\data"

os.makedirs(destination, exist_ok=True)

for file in os.listdir(source):
    src_path = os.path.join(source, file)
    dst_path = os.path.join(destination, file)
    shutil.move(src_path, dst_path)
    print(f"Moved: {file}")

print("\nAll 15 CSV files moved to:", destination)

Moved: ancestry_prediction.csv
Moved: cibersort.csv
Moved: circular_RNA.csv
Moved: clinical.csv
Moved: CNV.csv
Moved: followup.csv
Moved: hla_typing.csv
Moved: medical_history.csv
Moved: miRNA.csv
Moved: phosphoproteomics.csv
Moved: proteomics.csv
Moved: somatic_mutation.csv
Moved: transcriptomics.csv
Moved: tumor_purity.csv
Moved: xcell.csv

All 15 CSV files moved to: C:\Users\varsh\Documents\R\cptac_pdac_pca\data